name: AndroidBuild
on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Setup Java JDK
        uses: actions/setup-java@v4.5.0
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Ensure gradlew is executable
        run: |
         chmod +x gradlew
         ls -l gradlew  # Optional: check permissions

      - name: Build with Gradle
        run: ./gradlew build

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.4.3
        with:
          name: GitHubCI_CD.apk
          path: app/build/outputs/apk/debug/app-debug.apk

      - name: Send Email Notification
        if: success()  # Only send email if previous steps were successful
        uses: dawidd6/action-send-mail@v3.0.0
        with:
            smtp-server: ${{ secrets.SMTP_SERVER }}
            smtp-port: ${{ secrets.SMTP_PORT }}
            smtp-user: ${{ secrets.SMTP_USER }}
            smtp-password: ${{ secrets.SMTP_PASSWORD }}
            subject: "APK Build Successful"
            body: "The APK has been successfully built. You can download it from the artifacts."
            to: ${{ secrets.TO_EMAIL }}
            attachments: app/build/outputs/apk/debug/app-debug.apk